
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/glade/u/apps/derecho/25.10/spack/opt/spack/cmake/3.31.8/gcc/12.5.0/jijp/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.4.0-150600.23.53-default - x86_64
